### PR TITLE
Update Microsoft.IdentityModel dependencies

### PR DESCRIPTION
**Pull request by eerhardt**
Update to 7.0.0-preview3

cc @captainsafia @jennyf19

### CODE REVIEW

**Comment by mthalman** [comment]
The patch at https://github.com/dotnet/source-build-externals/blob/main/patches/azure-activedirectory-identitymodel-extensions-for-dotnet/0001-fix-for-source-build.patch needs to be rebaselined.

**Comment by mthalman** [comment]
It's reporting prebuilts for:

```
Microsoft.CSharp.4.5.0
System.Security.Cryptography.Cng.4.5.0
```

These will need to be added to [SBRP](https://github.com/dotnet/source-build-reference-packages).

**Comment by eerhardt** [comment]
> It's reporting prebuilts for:
> 
> ```
> Microsoft.CSharp.4.5.0
> System.Security.Cryptography.Cng.4.5.0
> ```
> 
> These will need to be added to [SBRP](https://github.com/dotnet/source-build-reference-packages).

I thought it wasn't going to care about those 2 packages, since they are not used to build for net8.0. But I guess I was wrong.

I've updated the versions to what we used in 8.0-preview7. So we shouldn't need to touch SBRP.

**Review by mthalman — APPROVED** [review]

**Comment by MichaelSimons** [comment]
> @MichaelSimons @mthalman - This change will need to get into 8.0-rc2 (it is too late to get it into rc1). I'm not sure when the timing of this change can happen, since it doesn't appear that source-build-externals has an 8.0 branch.

Is this pressing?  I would prefer to wait a few more day until we have an rc1 build.

**Comment by eerhardt** [comment]
> Is this pressing? I would prefer to wait a few more day until we have an rc1 build.

It's critical to get this into rc2 by the time it ships. We can wait a few days, if necessary. But I don't want to push it until rc1 ships because that is the same time rc2 locks down.

Just an FYI - we will be doing this at least 1 more time before we ship 8.0 GA, because IdentityModel will need to release a stable `7.0.0` version, which .NET 8.0 will depend on.

**Pull request merged**
