### PR TITLE
Remove Application-Insights 2.21

### PR DESCRIPTION
**Pull request by ellahathaway**
Closes https://github.com/dotnet/source-build/issues/4248

Now that the [application-insights patch in Arcade](https://github.com/dotnet/installer/pull/19160) has been removed, we can remove application-insights 2.21 from SBE.

### CODE REVIEW

**Review by mthalman — COMMENTED** [review]
I question whether we should rename to a versionless pattern because it's just going to need to be versioned the next time we need to upgrade.

**Comment by ellahathaway** [comment]
> I question whether we should rename to a versionless pattern because it's just going to need to be versioned the next time we need to upgrade.

I'm impartial about this. On one hand, I could argue that we should version all the repos if possible. On the other hand, it is added work to rename the submodule each time we have to upgrade.

**Comment by MichaelSimons** [comment]
If we updated [this line](https://github.com/dotnet/arcade/blob/main/Directory.Packages.props#L81) to use a version property, then arcade would float their AppInsights version and we wouldn't have this problem(needing to support multiple versions) with future upgrades (unless there is an breaking change).

**Review by MichaelSimons — APPROVED** [review]

**Comment by mthalman** [comment]
> I'm impartial about this. On one hand, I could argue that we should version all the repos if possible. On the other hand, it is added work to rename the submodule each time we have to upgrade.

I don't think it's necessary to version all the repos because most of them do not have scenarios where it's necessary to define multiple versions of the package. This one is special because of Arcade.

**Pull request merged**
