### PR TITLE
Update IdentityModel to 7.4.1

### PR DESCRIPTION
**Pull request by wtgodbe**
For https://github.com/dotnet/aspnetcore/pull/54601

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mthalman @MichaelSimons PTAL (For some reason I can't request reviews in the PR)

**Review by MichaelSimons — APPROVED** [review]

**Comment by wtgodbe** [comment]
Not sure how to investigate this error, did I do something wrong?

>   EXEC : error : src/Microsoft.IdentityModel.Protocols/Microsoft.IdentityModel.Protocols.csproj: patch does not apply [/__w/1/s/artifacts/sb/src/repo-projects/azure-activedirectory-identitymodel-extensions-for-dotnet.proj]

**Comment by MichaelSimons** [comment]
I forgot to mention this guidance - https://github.com/dotnet/source-build-externals?tab=readme-ov-file#updating-an-external-component-to-a-newer-version

**Comment by wtgodbe** [comment]
@eerhardt @MichaelSimons where can I find info on how to fix the patch files? It's not obvious to me how those get created or what they correspond to

**Comment by ellahathaway** [comment]
> where can I find info on how to fix the patch files? It's not obvious to me how those get created or what they correspond to. My local build failed in the same way as CI

The [patching guidelines documentation](https://github.com/dotnet/source-build/blob/main/Documentation/patching-guidelines.md) described the process pretty well.

When a patch fails, I begin by investigating the content of the patch. If the content is no longer applicable (i.e. the new version implemented the patched code), I'll delete the patch. Otherwise, make the patched changes to the new version, create the new patch, and delete the old patch.

**Comment by MichaelSimons** [comment]
I just opened a PR to include steps to manually apply patches and the cmd for easily creating/updating patches.  https://github.com/dotnet/source-build-externals/pull/301.  Please provide feedback.

**Comment by wtgodbe** [comment]
@MichaelSimons I ran `extract-patches.sh` from the `azure-activedirectory-identitymodel-extensions-for-dotnet` dir & it just deleted the pre-existing .patch files without creating any new ones - am I doing something wrong?

**Comment by MichaelSimons** [comment]
> @MichaelSimons I ran `extract-patches.sh` from the `azure-activedirectory-identitymodel-extensions-for-dotnet` dir & it just deleted the pre-existing .patch files without creating any new ones - am I doing something wrong?

Did you make any changes?  They have to be committed.

**Comment by wtgodbe** [comment]
Looks like they removed `updateAssemblyInfo.sh` in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2494. I deleted the patch, but @mthalman I see you added that patch in https://github.com/dotnet/source-build-externals/pull/199 - how can I test if their new method of setting `AssemblyVersion` will fail in full VMR source build?

**Comment by wtgodbe** [comment]
@mthalman @MichaelSimons I don't have permissions to merge here, could one of you click the button?

**Pull request merged**
