### PR TITLE
Update to IdentityModel 7.1.2

### PR DESCRIPTION
**Pull request by mthalman**

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Is this a merge from the temporary internal repo?

**Comment by mthalman** [comment]
> Is this a merge from the temporary internal repo?

Yes. It was necessary to revert the change to the .submodules file to prevent it from still pointing to the internal repo.

**Comment by mmitche** [comment]
> > Is this a merge from the temporary internal repo?
> 
> Yes. It was necessary to revert the change to the .submodules file to prevent it from still pointing to the internal repo.

Great!

**Pull request merged**
