### PR TITLE
Update IdentityModel submodule to preview2

### PR DESCRIPTION
**Pull request by jennyf19**

### CODE REVIEW

**Comment by mthalman** [comment]
@jennyf19 - Looks like this causes a prebuilt for Newtonsoft.Json.13.0.3. This version of that package needs to be added to https://github.com/dotnet/source-build-reference-packages. You can follow the instructions in the README there for how to do that. Once the PR for that gets merged, it will produce a new version of the SBRP package that will get merged into this repo. Once that happens, we can incorporate that change into this PR and we should be good.

**Comment by MichaelSimons** [comment]
> @jennyf19 - Looks like this causes a prebuilt for Newtonsoft.Json.13.0.3. This version of that package needs to be added to https://github.com/dotnet/source-build-reference-packages. You can follow the instructions in the README there for how to do that. Once the PR for that gets merged, it will produce a new version of the SBRP package that will get merged into this repo. Once that happens, we can incorporate that change into this PR and we should be good.

I think a better solution is to upgrade the version we are source-building to be 13.0.3.  There appear to be several repo on this version already (razor, fsharp, roslyn, etc).  We are source-build 13.0.1.  This repo resides in https://github.com/dotnet/source-build-externals but the upgrade should be done in a stand-alone PR.

**Comment by jennyf19** [comment]
closing as we cannot ship w/this dependency. We will open another one once we have newtonsoft completely removed. Thanks for your help today @mthalman

**Comment by MichaelSimons** [comment]
> closing as we cannot ship w/this dependency. We will open another one once we have newtonsoft completely removed. 

@jennyf19 - what is the backstory here?  I'm curious why this dependency can't be shipped.

**Pull request closed without merging**
